spring:
  application:
    name: todolist
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:h2:file:./src/main/resources/data/todo_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: todolist-group
    topic: todoservice-topic